ProjectBootcamp/Models/Video.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjectBootcamp.Models
{
    [Table("Video")]
    public class Video
    {
        [Key] public int Id { get; set; }

        [DisplayName("Titel")] [Required] public string Title { get; set; }

        [DisplayName("Descriptie")] [Required] public string Description { get; set; }

        public int Views { get; set; }
        public string Url { get; set; }
        public byte Activated { get; set; }

        [ForeignKey("Course")] public int CourseId { get; set; }

        public virtual Course Course { get; set; }
        public virtual ICollection<VideoComment> VideoComments { get; set; }
        public virtual ICollection<StudentFiles> StudentFiles { get; set; }

        [DisplayName("Aangemaakt op")] public DateTime CreatedAt { get; set; } = DateTime.Now;

        [DisplayName("Aangepast op")] public DateTime UpdatedAt { get; set; } = DateTime.Now;

        public string TeacherFileName { get; set; }
    }

    public class VideoComment
    {
        [Key] public int Id { get; set; }

        [Required] public string Comment { get; set; }

        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }

        [DisplayName("Video")] public int VideoId { get; set; }

        [DisplayName("Gebruiker")] public string UserId { get; set; }

        [ForeignKey("VideoId")]
        [Column(Order = 1)]
        public Video Video { get; set; }

        [ForeignKey("UserId")]
        [Column(Order = 2)]
        public virtual ApplicationUser User { get; set; }
    }

    public class StudentFiles
    {
        [Key] public int Id { get; set; }

        [Required] public string FileName { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public DateTime UpdatedAt { get; set; } = DateTime.Now;
        public bool Submitted { get; set; } = false;

        [DisplayName("Video")] public int VideoId { get; set; }

        [DisplayName("Gebruiker")] public string UserId { get; set; }

        [ForeignKey("VideoId")]
        [Column(Order = 1)]
        public virtual Video Video { get; set; }

        [ForeignKey("UserId")]
        [Column(Order = 2)]
        public virtual ApplicationUser User { get; set; }
    }
}

ProjectBootcamp/Controllers/VideosController.cs
using System;
using System.IO;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using NLog;
using ProjectBootcamp.DAL;
using ProjectBootcamp.Models;

namespace ProjectBootcamp.Controllers
{
    public class VideosController : Controller
    {
        private readonly ILogger _logger;
        private readonly IVideoRepository _videoRepository;

        public VideosController(IVideoRepository videoRepository, ILogger logger)
        {
            _videoRepository = videoRepository;
            _logger = logger;
        }

        // GET: Videos/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            ViewBag.Videos = await _videoRepository.LoadVideo();
            var video = await _videoRepository.GetVideoById(id);
            if (video == null) return HttpNotFound();

            if (Directory.Exists(HttpContext.ApplicationInstance.Server.MapPath("~") + "Uploads/courses/course_" +
                                 video.CourseId + "/videoid_" + id))
            {
                var filePaths = Directory.GetFiles(HttpContext.ApplicationInstance.Server.MapPath("~") +
                                                   "Uploads/courses/course_" + video.CourseId + "/videoid_" + id);
                ViewBag.FilePaths = filePaths;
            }
            else
            {
                ViewBag.FilePaths = null;
            }

            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            return View(video);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Details(int? id,
            [Bind(Include = "Id,Comment,UserId,VideoId,CreatedAt,UpdatedAt")]
            VideoComment videoComment)
        {
            try
            {
                if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                var video = await _videoRepository.GetVideoById(id);
                if (video != null)
                    await _videoRepository.InsertVideoComments(video, User.Identity.GetUserId(), videoComment);
                return RedirectToAction("Details");
            }
            catch (Exception e)
            {
                _logger.Error(e);
                throw;
            }
        }

        // POST: Videos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(
            [Bind(Include = "Id,Title,Description,Views,Activated,CourseId,CreatedAt,UpdatedAt,Url")]
            Video video)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _videoRepository.InsertVideo(video);
                    return Redirect(Request.UrlReferrer?.ToString()); // redirects to previous page
                }

                return Redirect(Request.UrlReferrer?.ToString()); // redirects to previous page
            }
            catch (Exception e)
            {
                _logger.Error(e);
                throw;
            }
        }

        // GET: Videos/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var video = await _videoRepository.GetVideoById(id);
            if (video == null) return HttpNotFound();
            return View(video);
        }

        // POST: Videos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(
            [Bind(Include = "Id,Title,Description,Views,Activated,CourseId,CreatedAt,UpdatedAt,Url")]
            Video video)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _videoRepository.UpdateVideo(video);
                    return Redirect(Request.UrlReferrer?.ToString()); // redirects to previous page
                }

                return View(video);
            }
            catch (Exception e)
            {
                _logger.Error(e);
                throw;
            }
        }

        // POST: Videos/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var video = await _videoRepository.GetVideoById(id);
                if (video != null) await _videoRepository.DeleteVideo(video);
                return Redirect(Request.UrlReferrer?.ToString()); // redirects to previous page
            }
            catch (Exception e)
            {
                _logger.Error(e);
                throw;
            }
        }

        // POST: Videos/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteComment([Bind(Include = "Id,CreatedAt,UpdatedAt,Comment,VideoId,UserId")]
            int id)
        {
            try
            {
                var video = await _videoRepository.GetVideoCommentById(id);
                if (video != null) await _videoRepository.DeleteVideoComment(video);
                return Redirect(Request.UrlReferrer?.ToString()); // redirects to previous page
            }
            catch (Exception e)
            {
                _logger.Error(e);
                throw;
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) _videoRepository.Dispose();
            base.Dispose(disposing);
        }
    }
}

ProjectBootcamp/Views/Videos/Details.cshtml
@using Microsoft.AspNet.Identity
@model ProjectBootcamp.Models.Video

@{
    <link href="~/Content/Css/video.css" rel="stylesheet"/>
}

<div class="offset-md-1 row">
    <div class="mt-3 col-12 col-md-10 col-lg-7">
        <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" allowfullscreen
                    src="https://www.youtube.com/embed/@Html.DisplayName(Model.Url)">
            </iframe>
        </div>
        <h5 class="mt-2 text-left">
            @Html.DisplayName(Model.Title)
            <div id="rating" class="col-auto float-right">
                <i class="far fa-star star" aria-hidden="true"></i>
                <i class="far fa-star star" aria-hidden="true"></i>
                <i class="far fa-star star" aria-hidden="true"></i>
                <i class="far fa-star star" aria-hidden="true"></i>
                <i class="far fa-star star" aria-hidden="true"></i>
            </div>
        </h5>

        <div id="videoContent" class="mt-5">
            <p>@Html.DisplayName(Model.Description)</p>
            <hr>
        </div>
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">
                    <i class="far fa-comment"></i>
                    Comments
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">
                    <i class="far fa-file"></i>
                    Bestanden
                </a>
            </li>
        </ul>

    </div>
    <div class="mt-3 col-12 col-md-10 col-lg-4 pre-scrollable" style="max-height: 500px">
        <h6>@Html.DisplayName(Model.Course.Title) video's</h6>
        @foreach (var item in Model.Course.Videos)
        {
            <a class="" href="/Videos/Details/@Html.DisplayName(item.Id.ToString())">

                <div style="clear: left;">
                    <p style="float: left;">
                        <img class="thumbnail pull-left mr-2"
                             src="http://i3.ytimg.com/vi/@Html.DisplayName(item.Url)/hqdefault.jpg"
                             alt="Thumbnail van video" style="height: 95px; margin-right: 15px; width: 185px;">
                    </p>
                    <p>
                        @Html.DisplayName(item.Title) <a class="badge badge-success" style="color: white">Bekeken</a>
                    </p>
                    <p class="sideVideoDescription" style="color: gray">@item.Description</p>
                </div>
            </a>
        }
    </div>


    <div class="tab-content" id="myTabContent" style="padding-top: 15px">
        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
            <div class="col-12">
                <div style="padding-top: 10px">
                    <div class="card border-0">
                        <div class="card-body ">
                            <div class="row">
                                <div class="col-2">
                                    <img src="https://image.ibb.co/jw55Ex/def_face.jpg" class="img img-rounded img-fluid"/>
                                </div>
                                <div class="col-md-10">
                                    @using (Html.BeginForm("Details", "Videos", FormMethod.Post, new {}))
                                    {
                                        @Html.AntiForgeryToken()
                                        <div class="form-group">
                                            <textarea name="Comment" class="form-control" id="exampleFormControlTextarea1" rows="3" required></textarea>
                                        </div>
                                        <p>
                                            <button type="submit" class="float-right btn btn-outline-primary ml-2"> plaats</button>
                                        </p>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                @foreach (var item in Model.VideoComments)
                {
                    <hr>

                    if (item.UserId == User.Identity.GetUserId() || item.UserId == User.Identity.GetUserId() || User.IsInRole("Admin") || User.IsInRole("Teacher"))
                    {
                        @Html.AntiForgeryToken()
                        <input name="ID" value="@item.Id" type="hidden"/>
                        <button type="submit" class="float-right btn text-danger btn-danger; border-0" style="background: white" data-toggle="modal" data-target="#comment-@item.Id">
                            <i class="fa fa-trash"></i>
                        </button>
                    }

                    <div style="padding-top: 10px">
                        <div class="card border-0">
                            <div class="card-body ">
                                <div class="row">
                                    <div class="col-2">
                                        <img src="https://image.ibb.co/jw55Ex/def_face.jpg" class="img img-rounded img-fluid"/>
                                    </div>
                                    <div class="col-10">
                                        <p>
                                            <a class="float-left">
                                                <strong>@Html.DisplayFor(Model => item.User.FirstName) @Html.DisplayFor(Model => item.User.LastName)</strong>
                                                <a class="text-secondary float-right">@Html.DisplayName(item.CreatedAt.ToString("dd/MM/yyyy H:mm"))</a>
                                            </a>
                                        </p>
                                        <div class="clearfix"></div>
                                        <p>
                                            @item.Comment

                                        </p>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                    <!-- Modal -->
                    <div class="modal fade" id="comment-@item.Id" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLongTitle">Weet u zeker dat u uw comment wil verwijderen? </h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p>@item.Comment</p>
                                </div>
                                <div class="modal-footer">
                                    @using (Html.BeginForm("DeleteComment", "Videos", FormMethod.Post))
                                    {
                                        @Html.AntiForgeryToken()
                                        <input name="ID" value="@item.Id" type="hidden"/>
                                        <button class="btn btn-danger">Verwijder</button>
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Sluit</button>
                                    }
                                </div>

                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">

            @if (ViewBag.FilePaths == null)
            {
                <p>Er zijn momenteel geen bestanden beschikbaar...</p>
            }
            else
            {
                var name = "";
                foreach (var item in ViewBag.FilePaths)
                {
                    string test = item.ToString();
                    name = test.Substring(test.LastIndexOf(@"\"));


                    <hr>
                    <a href='\Uploads\courses\course_@Model.CourseId\videoid_@Model.Id\@name' point="blank" download>
                        <p>
                            <i class="fas fa-file-word"></i> @name</p>
                    </a>
                }
            }


        </div>
    </div>

</div>

ProjectBootcamp/Views/Videos/Edit.cshtml
@model ProjectBootcamp.Models.Video

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Video</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Title, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Description, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Views, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Views, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Views, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Activated, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Activated, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Activated, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CourseId, "CourseId", new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.DropDownList("CourseId", null, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.CourseId, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedAt, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedAt, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.CreatedAt, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UpdatedAt, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.UpdatedAt, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.UpdatedAt, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Details")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}