ProjectBootcamp/Controllers/CoursesController.cs
using System;
using System.IO;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using NLog;
using ProjectBootcamp.DAL;
using ProjectBootcamp.Models;

namespace ProjectBootcamp.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ICourseRepository _courseRepository;
        private readonly ILogger _logger;

        public CoursesController(ICourseRepository courseRepository, ILogger logger)
        {
            _courseRepository = courseRepository;
            _logger = logger;
        }

        // GET: Courses
        [Authorize]
        public async Task<ActionResult> Index(int? page)
        {
            var userCourses = _courseRepository.LoadUserCourses();
            // show ur own courses
            if (!User.IsInRole("Admin"))
            {
                var loggedInStudentId = User.Identity.GetUserId();
                userCourses = _courseRepository.GetUserCourseByUserId(loggedInStudentId);
            }

            return View(await _courseRepository.GetUserCourses(page, userCourses));
        }

        // GET: Courses/Details/5
        [Authorize]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var userCourse = await _courseRepository.GetCourseById(id);
            ViewBag.UserId = new SelectList(await _courseRepository.GetUsersNotInACourse(id), "Id", "Email");
            if (userCourse == null) return HttpNotFound();

            ViewBag.Id = id;
            ViewBag.Student = await _courseRepository.GetStudentFiles(User.Identity.GetUserId());

            return View(userCourse);
        }

        // POST: Courses/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        [Authorize(Roles = "Admin, Teacher")]
        public async Task<ActionResult> Create([Bind(Include = "Id,CourseId,UserId")] UserCourse userCourse)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _courseRepository.InsertUserCourse(userCourse.Id, userCourse.UserId);
                    return Redirect(Request.UrlReferrer?.ToString());
                }

                return Redirect(Request.UrlReferrer?.ToString());
            }
            catch (Exception e)
            {
                _logger.Error(e);
                throw;
            }
        }

        // POST: Courses/CreateCourse
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        [Authorize(Roles = "Admin, Teacher")]
        public async Task<ActionResult> CreateCourse(
            [Bind(Include = "Id,Title,Description,CreatedAt,UpdatedAt,ColorId")]
            Course course)
        {
            try
            {
                if (!ModelState.IsValid) return Redirect(Request.UrlReferrer?.ToString());
                await _courseRepository.InsertCourse(course, course.Id, User.Identity.GetUserId());
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                _logger.Error(e);
                throw;
            }
        }

        // POST: Courses/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        [Authorize(Roles = "Admin, Teacher")]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Title,Description,CreatedAt,UpdatedAt,ColorId")]
            Course course)
        {
            try
            {
                if (!ModelState.IsValid) return Redirect(Request.UrlReferrer?.ToString());
                await _courseRepository.UpdateCourse(course);
                return Redirect(Request.UrlReferrer?.ToString());
            }
            catch (Exception e)
            {
                _logger.Error(e);
                throw;
            }
        }

        // POST: Courses/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        [Authorize(Roles = "Admin, Teacher")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var userCourse = await _courseRepository.GetUserCourseById(id);
                if (User.Identity.GetUserId() == userCourse?.UserId) return RedirectToAction("Index");
                await _courseRepository.DeleteUserCourse(userCourse);
                return Redirect(Request.UrlReferrer?.ToString()); // redirects to previous page
            }
            catch (Exception e)
            {
                _logger.Error(e);
                throw;
            }
        }

        // POST: Courses/DeleteCourse/5
        [HttpPost]
        [ActionName("DeleteCourse")]
        [ValidateAntiForgeryToken]
        [Authorize]
        [Authorize(Roles = "Admin, Teacher")]
        public async Task<ActionResult> DeleteCourseConfirmed(int id)
        {
            try
            {
                var course = await _courseRepository.GetCourseById(id);
                await _courseRepository.DeleteCourse(course);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                _logger.Error(e);
                throw;
            }
        }

        //Uploads A file for a Teacher
        [HttpPost]
        public ActionResult UploadFile(HttpPostedFileBase file, int? id, int? videoId)
        {
            try
            {
                if (file.FileName == string.Empty) return Redirect(Request.UrlReferrer?.ToString());
                var folder = Server.MapPath("~/Uploads/courses/course_" + id + "/videoid_" + videoId);
                if (!Directory.Exists(folder)) Directory.CreateDirectory(folder);
                var fileName = Path.GetFileName(file.FileName);
                var path = Path.Combine(Server.MapPath("~/Uploads/courses/course_" + id + "/videoid_" + videoId),
                    fileName ?? throw new InvalidOperationException());
                file.SaveAs(path);

                return Redirect(Request.UrlReferrer?.ToString());
            }
            catch (Exception e)
            {
                _logger.Error(e);
                throw;
            }
        }

        //Uploads a file for a student
        [HttpPost]
        public async Task<ActionResult> UploadFileStudent(HttpPostedFileBase file, string student, int? courseid,
            int videoId, string userid)
        {
            try
            {
                if (file.FileName == string.Empty) return Redirect(Request.UrlReferrer?.ToString());
                var folder = Server.MapPath("~/Uploads/students/" + student + "/courses/" + "/courseid_" + courseid +
                                            "/videos/" + "/videoid_" + videoId);
                if (!Directory.Exists(folder)) Directory.CreateDirectory(folder);
                var fileName = Path.GetFileName(file.FileName);
                var path = Path.Combine(
                    Server.MapPath("~/Uploads/students/" + student + "/courses/" + "/courseid_" + courseid +
                                   "/videos/" + "/videoid_" + videoId),
                    fileName ?? throw new InvalidOperationException());
                var objfiles = new StudentFiles
                {
                    FileName = fileName,
                    VideoId = videoId,
                    UserId = userid,
                    Submitted = true
                };
                ViewBag.FileName = fileName;
                await _courseRepository.InsertStudentFiles(objfiles);
                file.SaveAs(path);

                return Redirect(Request.UrlReferrer?.ToString());
            }
            catch (Exception e)
            {
                _logger.Error(e);
                throw;
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) _courseRepository.Dispose();
            base.Dispose(disposing);
        }
    }
}

ProjectBootcamp/Controllers/ForumsController.cs
using System;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using NLog;
using ProjectBootcamp.DAL;
using ProjectBootcamp.Models;

namespace ProjectBootcamp.Controllers
{
    public class ForumsController : Controller
    {
        private readonly IForumRepository _forumRepository;
        private readonly ILogger _logger;

        public ForumsController(IForumRepository forumRepository, ILogger logger)
        {
            _forumRepository = forumRepository;
            _logger = logger;
        }

        // GET: Forums
        public async Task<ActionResult> Index(int? page)
        {
            ViewBag.Forums = await _forumRepository.GetForums(page);
            return View(ViewBag.Forums);
        }

        // GET: Forums/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            try
            {
                if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                var forum = await _forumRepository.GetForumById(id);

                if (forum == null) return HttpNotFound();
                return View(await _forumRepository.GetForumById(id));
            }
            catch (Exception e)
            {
                _logger.Error(e);
                throw;
            }
        }

        // POST: Forums/details
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Details(int? id,
            [Bind(Include = "Id,Comment,UserId,ForumId,CreatedAt,UpdatedAt")]
            ForumComment forumComment)
        {
            try
            {
                var forum = await _forumRepository.GetForumById(id);
                if (!ModelState.IsValid)
                    if (forum != null)
                        return RedirectToAction("Details", new {id = (int?) forum.Id});
                if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                await _forumRepository.InsertForumComment(id, forumComment, User.Identity.GetUserId());

                return RedirectToAction("Details", new {id = forum?.Id});
            }
            catch (Exception e)
            {
                _logger.Error(e);
                throw;
            }
        }

        [Authorize]
        [HttpPost]
        [ActionName("DeleteComment")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteComment(int id)
        {
            try
            {
                var forumComment = await _forumRepository.GetForumCommentById(id);

                if (forumComment?.UserId == User.Identity.GetUserId() ||
                    forumComment?.Forum.UserId == User.Identity.GetUserId() || User.IsInRole("Admin") ||
                    User.IsInRole("Teacher")) await _forumRepository.DeleteForumComment(id);

                if (forumComment != null) return RedirectToAction("Details", new {id = forumComment.ForumId});
            }
            catch (Exception e)
            {
                _logger.Error(e);
                throw;
            }

            _logger.Error(typeof(InvalidOperationException));
            throw new InvalidOperationException();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> LikeComment(int id)
        {
            try
            {
                var forumComment = await _forumRepository.GetForumCommentById(id);
                if (!ModelState.IsValid)
                    if (forumComment != null)
                        return RedirectToAction("Details", new {id = forumComment.ForumId});

                await _forumRepository.UpvoteComment(id, User.Identity.GetUserId());

                if (forumComment != null) return RedirectToAction("Details", new {id = forumComment.ForumId});
            }
            catch (Exception e)
            {
                _logger.Error(e);
                throw;
            }

            _logger.Error(typeof(InvalidOperationException));
            throw new InvalidOperationException();
        }

        [Authorize]
        [HttpPost]
        [ActionName("DeleteLikeFromComment")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteLikeFromComment(int id)
        {
            try
            {
                var commentHasUpVotes = await _forumRepository.GetForumCommentHasUpvotes(id);
                if (commentHasUpVotes == null) throw new InvalidOperationException();
                var forumComment = await _forumRepository.GetForumCommentById(commentHasUpVotes.CommentId);


                if (commentHasUpVotes.UserId == User.Identity.GetUserId())
                    await _forumRepository.DownvoteComment(commentHasUpVotes);

                if (forumComment != null) return RedirectToAction("Details", new {id = forumComment.ForumId});
            }
            catch (Exception e)
            {
                _logger.Error(e);
                throw;
            }

            _logger.Error(typeof(InvalidOperationException));
            throw new InvalidOperationException();
        }


        /// Edit forum comments
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditComment([Bind(Include = "Id,Comment")] ForumComment forumComment)
        {
            try
            {
                var currentComment = await _forumRepository.CurrentForumComment(forumComment);
                if (currentComment == null) return HttpNotFound();
                if (!ModelState.IsValid) return RedirectToAction("Details", new {id = currentComment.ForumId});
                if (currentComment.UserId != User.Identity.GetUserId())
                    return RedirectToAction("Details", new {id = currentComment.ForumId});
                currentComment.Comment = forumComment.Comment;
                await _forumRepository.SaveChangesAsync();

                return RedirectToAction("Details", new {id = currentComment.ForumId});
            }
            catch (Exception e)
            {
                _logger.Error(e);
                throw;
            }
        }

        // POST: Forums/Create
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Title,Description,UserId,CreatedAt,UpdatedAt")]
            Forum forum)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _forumRepository.InsertForum(User.Identity.GetUserId(), forum);
                    return RedirectToAction("Index");
                }

                return View(forum);
            }
            catch (Exception e)
            {
                _logger.Error(e);
                throw;
            }
        }

        // POST: Forums/Edit/5
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Title,Description")]
            Forum forum)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var currentForum = await _forumRepository.CurrentForum(forum);
                    if (currentForum == null)
                        return HttpNotFound();

                    if (currentForum.ApplicationUser.Id != User.Identity.GetUserId() && !User.IsInRole("Admin") &&
                        !User.IsInRole("Teacher")) return RedirectToAction("Details", new {currentForum.Id});
                    await _forumRepository.UpdateForum(currentForum, forum.Title, forum.Description, DateTime.Now);

                    return RedirectToAction("Details", new {currentForum.Id});
                }

                return View(forum);
            }
            catch (Exception e)
            {
                _logger.Error(e);
                throw;
            }
        }

        // POST: Forums/Delete/5
        [Authorize]
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var forum = await _forumRepository.GetForumById(id);
                if (forum?.ApplicationUser.Id != User.Identity.GetUserId() && !User.IsInRole("Admin") &&
                    !User.IsInRole("Teacher")) return RedirectToAction("Index");
                await _forumRepository.DeleteForum(forum);

                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                _logger.Error(e);
                throw;
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) _forumRepository.Dispose();
            base.Dispose(disposing);
        }
    }
}

ProjectBootcamp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/Css/Hometemplate.css")
    @Styles.Render("~/Content/Css/main.css")


    <link href="~/Content/fontawesome-all.min.css" rel="stylesheet"/>
    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts -->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
    <link href="vendor/simple-line-icons/css/simple-line-icons.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins&display=swap" rel="stylesheet">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
</head>
<body>
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light bg-light static-top">
    <div class="container">
        <a class="navbar-brand" href="/">
            <img src="https://www.windesheim.nl/-/media/images/site-logos/windesheim-logo.png?h=108&la=nl-NL&w=170&hash=F1A9866917A2D98F8283D34D24B12FE3B471AEF1" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Home")" class="nav-link">Home</a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Courses")" class="nav-link">Courses</a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Forums")" class="nav-link">Forum</a>
                </li>
                @if (User.IsInRole("Admin"))
                {
                    <li class="nav-item ">
                        <a href="@Url.Action("Index", "Admin")" class="nav-link">Admin</a>
                    </li>
                }
                <li class="nav-item ">
                    <a href="@Url.Action("Contact", "Home")" class="nav-link">Contact</a>
                </li>
                @Html.Partial("_LoginPartial")
            </ul>
        </div>
    </div>
</nav>

@RenderBody()

<!-- Site footer -->
<footer class="site-footer mt-3">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <h6>About</h6>
                <p class="text-justify">Windesheim <i>Bootcamp courses</i> is an initiative to help the upcoming programmers with the code. Bootcamp focuses on providing the most efficient code or snippets as the code wants to be simple. We will help programmers build up concepts in different programming languages that include C, C++, Java, HTML, CSS, Bootstrap, JavaScript, PHP, Android, SQL and Algorithm.</p>
            </div>

            <div class="col-xs-6 col-md-3">
                <h6>Categories</h6>
                <ul class="footer-links">
                    <li>
                        <a href="@Url.Action("Index", "Home")">Home</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Courses")">Courses</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Forums")">Forum</a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Manage")">Account</a>
                    </li>
                </ul>
            </div>

            <div class="col-xs-6 col-md-3">
                <h6>Quick Links</h6>
                <ul class="footer-links">
                    <li>
                        <a href="@Url.Action("Contact", "Home")">Contact</a>
                    </li>
                    <li>
                        <a href="#">Contribute</a>
                    </li>
                    <li>
                        <a href="#">Privacy Policy</a>
                    </li>
                    <li>
                        <a href="#">Sitemap</a>
                    </li>
                </ul>
            </div>
        </div>
        <hr>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-6 col-xs-12">
                <p class="copyright-text">
                    Copyright &copy; @DateTime.Now.Year
                    <a href="https://www.windesheim.nl/" target="_blank">Windesheim Bootcamp</a>.
                </p>
            </div>

            <div class="col-md-4 col-sm-6 col-xs-12">
                <ul class="social-icons">
                    <li>
                        <a class="facebook" href="#">
                            <i class="fab fa-facebook"></i>
                        </a>
                    </li>
                    <li>
                        <a class="twitter" href="#">
                            <i class="fab fa-twitter"></i>
                        </a>
                    </li>
                    <li>
                        <a class="dribbble" href="#">
                            <i class="fab fa-dribbble"></i>
                        </a>
                    </li>
                    <li>
                        <a class="linkedin" href="#">
                            <i class="fab fa-linkedin"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", false)
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


</body>
</html>